### ISSUE TITLE
Create Documents for Konzeptförderung

### ISSUE THREAD

**Issue by albertoelschlaegel** [Ultraschall-VR/Echosystem-Resonance#44]
https://miro.com/app/board/o9J_lWLgxGE=/

**Comment by DemianBasse** [comment]
**### ToDo:**
- Anlage_4_Trackrecord_Referenzprojekte
- Anlage_9_Vorlage_Kostenplan
- Anlage_10_Finanzierungsplan
- Analge_12_Einverständniserklärung
- Anlage_14_Fördersituation_Historie
- Anlage_15_Handelsregisterauszug_Gewerbenachweis
- Bankauskunft_PwC
- Beistellungserklärung_Antragsteller

**Comment by DemianBasse** [comment]
- [ ] Naming Convention von den Files
- [ ] Versand-ready machen
- [ ] Rückstellungserklärungen für: Albert, Alex, Nina
- [ ] Unterschrift Bank für PwC
